binanceApp/urls.py
from django.urls import path
from binanceApp import views
app_name = 'binanceApp'


urlpatterns = [
    path('', views.order_list, name="order_list"),
    path('ma/', views.ma, name='ma'),
    path('order/create/', views.order_create, name='order_create')
    ]

binance_django/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('binanceApp.urls', namespace='binance'))
]

binanceApp/models.py
from django.db import models
# Create your models here.


class Order(models.Model):
    order = models.CharField(max_length=50)
    status = models.BooleanField(default=False)
    range_price = models.DecimalField(max_digits=10, decimal_places=2, unique=True)
    btc_count = models.DecimalField(max_digits=10, decimal_places=4, default=0)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    order_id = models.IntegerField(default=None)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return 'Order {}'.format(self.id)

binanceApp/forms.py
from django import forms
from binanceApp.models import Order


class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ('order',
                  'range_price',
                  'btc_count')
        widgets = {
            'order': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Order name'}),
            'range_price': forms. NumberInput(attrs={'class': 'form-control', 'placeholder': 'Range price'}),
            'btc_count': forms. NumberInput(attrs={'class': 'form-control', 'placeholder': 'BTC count'}),
        }
        labels = {
            'order': 'Order name',
            'range_price': 'Range price',
            'btc_count': 'BTC count',
        }

binanceApp/views.py
from django.shortcuts import render
from binance.client import Client
from django.http import JsonResponse
from django.template.loader import render_to_string
from binance.websockets import BinanceSocketManager
from binanceApp.forms import OrderCreateForm
from binanceApp.models import Order
from binance.enums import *


api_key = ''
secret_key = ''

client = Client(api_key, secret_key)

btc_price = {'error': False}
df1 = list()
sum_MA = 0
MA = 0


def to_fixed(num_obj, digits=0):
    return f"{num_obj:.{digits}f}"


def btc_trade_history(msg):
    global df1, sum_MA, MA
    if msg['k']['x']:
        df1.append(float(msg['k']['c']))
        print(df1)
        if len(df1) >= 8:
            sum_MA = sum(df1[len(df1)-2:len(df1)])
    if len(df1) >= 8:
        MA = float(to_fixed(sum_MA + float(msg['k']['c'])/9, digits=2))
        delta = float(to_fixed(MA - float(to_fixed(float(msg['k']['c']))), digits=2))
        if delta > 0:
            print(delta, '---')
            if Order.objects.filter(range_price=delta, status=False):
                print(delta, '---')
                buy_order = client.create_test_order(
                    symbol='BTCUSDT',
                    side=SIDE_BUY,
                    type=ORDER_TYPE_MARKET,
                    quantity=float(Order.objects.filter(range_price=delta, status=False).values()[0]['btc_count']))
                order = Order.objects.filter(range_price=delta, status=False).first()
                order.status = True
                order.order_id = buy_order['orderId']
                order.save()
            else:
                pass
        elif delta < 0:
            print(delta, '+++')
            if Order.objects.filter(range_price=delta, status=False):
                sell_order = client.create_test_order(
                    symbol='BTCUSDT',
                    side=SIDE_SELL,
                    type=ORDER_TYPE_MARKET,
                    quantity=float(Order.objects.filter(range_price=delta, status=False).values()[0]['btc_count'])
                    )
                order = Order.objects.filter(range_price=delta, status=False).first()
                order.status = True
                order.order_id = sell_order['orderId']
                order.save()
            else:
                pass
        if MA == float(msg['k']['c']):
            print("CLOSE")
            for obj in Order.objects.all():
                client.cancel_order(
                    symbol='BNBBTC',
                    orderId=obj.order_id
                    )

    else:
        pass


def order_list(request):
    orders_obj = Order.objects.all()
    content = {'orders': orders_obj, 'ma_obj': MA}
    return render(request, 'binance/list_binance.html', content)


def save_book_form(request, form, template_name):
    data = dict()
    print(MA)
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            data['form_is_valid'] = True
            orders = Order.objects.all()
            data['html_order_list'] = render_to_string('binance/partial_order_list.html',
                                                       {'orders': orders})
        else:
            data['form_is_valid'] = False
    context = {'form': form}
    data['html_form'] = render_to_string(template_name, context, request=request)
    data['MA'] = MA
    return JsonResponse(data)


def ma(request):
    data = dict()
    data['MA'] = MA
    return JsonResponse(data, safe=False)


def order_create(request):
    if request.method == 'POST':
        form = OrderCreateForm(request.POST)
    else:
        form = OrderCreateForm()
    return save_book_form(request, form, 'binance/partial_order_create.html')


client.get_avg_price(symbol='BNBBTC')
bsm = BinanceSocketManager(client)
conn_key = bsm.start_kline_socket('BTCUSDT', btc_trade_history, interval=Client.KLINE_INTERVAL_15MINUTE)
print(bsm.start())

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}{% endblock %}</title>
    <title>Title</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

    <script src="{% static 'js/main.js' %}"></script>

</head>


<body>
    <div>
        <h1>Квартиры</h1>
    </div>
    <div id="content">
        {% block content %}{% endblock %}
    </div>
</body>


</html>

templates/binance/list_binance.html
{% extends 'base.html' %}
{% block content %}
    <h1 class="page-header">Orders</h1>
        <p>
            <button type="button"
                    class="btn btn-primary js-create-order"
                    data-url="{% url 'binanceApp:order_create' %}">
              <span class="glyphicon glyphicon-plus"></span>
              New order
            </button>
        </p>
    <h1>MA</h1><h1 id = "ma_display"></h1>
    <table class="table" id="order-table">
    <thead>
      <tr>
        <th>#</th>
        <th>Title</th>
          <th>Status</th>
          <th>Date create</th>
          <th>Date update</th>
      </tr>
    </thead>
    <tbody>
    {% include 'binance/partial_order_list.html' %}

    </tbody>
  </table>


    <div class="modal fade" id="modal-order">
    <div class="modal-dialog">
      <div class="modal-content">
      </div>
    </div>
    </div>
{% endblock %}

templates/binance/partial_order_create.html
<form method="post" class="js-order-create-form" action="{% url "binanceApp:order_create" %}">
    {% csrf_token %}
    <div class="modal-header">
        <h4 class="modal-title">Create a new Oder</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close" id="closeForm">
            <span aria-hidden="true">&times;</span></button>
    </div>
    <div class="modal-body">
        {% for field in form %}
            <div class="fieldWrapper">
                {{ field.errors }}
                {{ field.label_tag }}
                {{ field }}
                {% if field.help_text %}
                <p class="help">{{ field.help_text|safe }}</p>
                {% endif %}
            </div>
        {% endfor %}
    </div>
        <div class="modal-footer">
            <button type="button" id="closeForm" class="btn btn-default" data-dismiss="modal">Close</button>
            <button type="submit" class="btn btn-primary">Create Order</button>
        </div>
</form>

templates/binance/partial_order_list.html
{% for order in orders %}
  <tr>
    <td>{{ order.id }}</td>
    <td>{{ order.order }}</td>
    <td>{{ order.status }}</td>
    <td>{{ order.created }}</td>
    <td>{{ order.updated }}</td>
    <td>{{ order.order_id }}</td>
    <td>{{ order.btc_count }}</td>
  </tr>
{% empty %}
  <tr>
    <td colspan="7" class="text-center bg-warning">No order</td>
  </tr>
{% endfor %}